language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn cobertura:cobertura
notifications:
  email:
    recipients:
      - carlos.tambascia@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

    after_success:
  - bash <(curl -s https://codecov.io/bash)